all:
  children:
    windows:
      children:
        estacoes_modelagem:
          hosts:
            MTZ_MODM08:
              ansible_host: 192.168.2.117
            MTZ_MED02:
              ansible_host: 192.168.2.71

        estacoes_ti:
          hosts:
            MTZ_TI10:
              ansible_host: 192.168.0.155

      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5986
        ansible_user: "{{ vault_win_admin_user }}"
        ansible_password: "{{ vault_win_admin_pass }}"