all:
  children:
    windows:
      children:
        estacoes_modelagem:
          hosts:
            MTZ_MODM08:
              ansible_host: 192.168.2.117
            MTZ_MED02:
              ansible_host: 192.168.2.71
            MTZ_MODM01:
              ansible_host: 192.168.1.148
            MTZ_MODTC03:
              ansible_host: 192.168.1.70

        estacoes_ti:
          hosts:
            MTZ_TI10:
              ansible_host: 192.168.0.155
            MTZ_TI02:
              ansible_host: 192.168.0.192
            MTZ_TI04:
              ansible_host: 192.168.0.153
            MTZ_TI11:
              ansible_host: 192.168.0.70

        estacoes_notas:
          hosts:
            MTZ_NOTAS01:
              ansible_host: 192.168.1.103
            MTZ_NOTAS02:
              ansible_host: 192.168.1.102

        estacoes_sac:
          hosts:
            MTZ_SAC01:
              ansible_host: 192.168.1.244
            MTZ_SAC04:
              ansible_host: 192.168.1.202
            MTZ_SAC05:
              ansible_host: 192.168.2.5
            MTZ_SAC06:
              ansible_host: 192.168.2.206
            MTZ_SAC09:
              ansible_host: 192.168.1.142          
            
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5986
        ansible_user: "{{ vault_win_admin_user }}"
        ansible_password: "{{ vault_win_admin_pass }}"
