---
- name: Instalar Oracle Client 10G
  hosts: windows
  gather_facts: false

  vars:
    origem_instaladores: "/opt/ansible/files/sistema/oracle"
    oracle_zip: "client-oracle-10g.zip"
    oracle_bat: "install-oracle-10g.bat"

  tasks:

    - name: Criar pasta temporária de instalação
      ansible.windows.win_file:
        path: C:\temp
        state: directory

    - name: Copiar zip do Oracle Client 10G
      ansible.windows.win_copy:
        src: "{{ origem_instaladores }}/{{ oracle_zip }}"
        dest: 'C:\temp\{{ oracle_zip }}'
      register: resultado_copia_zip

    - name: Descompactar arquivo
      community.windows.win_unzip:
        src: 'C:\temp\{{ oracle_zip }}'
        dest: C:\temp
        delete_archive: false
      register: resultado_unzip
      when: resultado_copia_zip is success

    - name: Copiar script de instalação
      ansible.windows.win_copy:
        src: "{{ origem_instaladores }}/{{ oracle_bat }}"
        dest: 'C:\temp\client-oracle-10g\{{ oracle_bat }}'
      register: resultado_copia_bat
      when: resultado_unzip is success

    - name: Executar instalação Oracle
      ansible.windows.win_command: "{{ oracle_bat }}"
      args:
        chdir: 'C:\temp\client-oracle-10g'
        creates: 'C:\oracle\product\10.2.0\client_1\bin\sqlplus.exe'
      async: 1800
      poll: 15
      register: resultado_oracle
      when: resultado_copia_bat is success

    - name: Relatório de instalação
      ansible.builtin.debug:
        msg:
          - "Cópia do ZIP ........ OK"
          - "Descompactação ....... OK"
          - "Instalação Oracle .... {{ 'OK' if resultado_oracle is success else 'FALHOU' }}"